# Netlify configuration for Next.js
[build]
  command = "next build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[dev]
  command = "next dev"

# Redirect all requests to Next.js
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
