import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="manifest" href="/manifest.json" />
          <meta name="theme-color" content="#0ea5e9" />
          <meta name="mobile-web-app-capable" content="yes" />
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta name="apple-mobile-web-app-status-bar-style" content="default" />
          <link rel="apple-touch-icon" href="/icon-192.png" />
          <link rel="icon" href="/favicon-2025.png" type="image/png" />
          <link rel="shortcut icon" href="/favicon-2025.png" type="image/png" />
        </head>
        <body
          className={`
            ${geistSans.variable} ${geistMono.variable} antialiased
          `}
          suppressHydrationWarning
        >
          <Toaster position="top-center" richColors closeButton />
          {children}
        </body>
      </html>
  );
}
